name: Build & Deploy

on: [push]

env:
  AZURE_WEBAPP_NAME: staging-bosengineers    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '5.8.x'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: Staging
    steps:

    - uses: actions/checkout@main  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Run Build
      run: dotnet build --no-restore -c Release 
    
    - name: Publish
      run: dotnet publish --no-build -c Release -o ./published
    
      
      
